### ISSUE TITLE
How to get hable tonemap

### ISSUE THREAD

**Issue by stefanrybacki** [so-rose/fast-hdr#1]
Hi there I was wondering how to get a tonemap matrix equivalent to `ffmpegs tonemap=hable` option.

I see that the coefficients seem to match hable coefficients, however the result is different than what ffmpegs `tonemap=hable` does.

**Comment by so-rose** [comment]
I did look around a bit, as the Hable tonemap is also what I'd ideally want.

However, as it's implemented now, Hable is not the global tonemapping operator that's implemented. I'm using a custom tonemapping curve, which aims to look a little like Uncharted.

I'd be happy to implement Hable, if you'd point me in the direction of a global tonemapping function that implements it. Unfortunately, fast-hdr can't do any local operations; that'd defeat the whole point of the hack.

**Comment by so-rose** [comment]
Seems I missed it! Apparently the Uncharted 2 TMO is what's referred to as "Hable":

https://64.github.io/tonemapping/

I might give it a quick go. Just commenting here so I remember.
